apiVersion: v1
kind: Service
metadata:
  name: weather-time-api-svc
  namespace: python-ci-cd-k8s
spec:
  selector:
    app: weather-time-api
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8000
  type: ClusterIP
